### ISSUE TITLE
Unable to find config.js file

### ISSUE THREAD

**Issue by Lyazz** [rafipiccolo/yggtorrent-api#1]
Hello there, as mentionned in the title, when I try to run the test.js file, an error occurs because it cannot find the config.js file. please help.

**Comment by rafipiccolo** [comment]
Hello,

You could easily guess what to put inside from reading the readme.
or from exemple.js :)
i can't give you mine, ofc, but here is an exemple :

```
module.exports = {
    host: 'https://yggtorrent.si',
    searchhost: 'https://www2.yggtorrent.si',
    username: 'xxxxx',
    password: 'xxxxx',
}
```

ps : i just released a new version.

If you trigger cloudflare bot detection you will get this message lost in a big html body : "Checking your browser before accessing"
