### ISSUE TITLE
error Error: Bad status code while searching : 503

### ISSUE THREAD

**Issue by xPiston** [rafipiccolo/yggtorrent-api#3]
Bonjour,
J'ai quelques soucis avec votre magnifique api, en effet celle-ci me return une erreur. Elle rentre en config avec cloudflare, l'anti-doss m'indique d'activer mon Javascript (sûrement cheeriojs).

[log.txt](https://github.com/rafipiccolo/yggtorrent-api/files/6215646/log.txt)

**Comment by rafipiccolo** [comment]
Salut,

Comme pour l'issue #2, je crain de ne pas avoir de solution toute prête.
ps: Cheeriojs est juste lequivalent de jquery. pour passer une protection ddos de ce type il faut un vrai navigateur.

Mais je peux proposer ça : 
1) se connecter une fois à la main via un navigateur, puis récupérer le cookie de cloudflare, puis l'injecter dans le script. Assez chiant mais ça doit marcher.
A priori ce code doit suffire : (le jar vient de cette lib : https://www.npmjs.com/package/tough-cookie)
const jar = request.jar();
cookies.forEach(cookie =>
    jar.setCookie(cookie)
);

2) sinon il est possible d'utiliser puppeteer pour simuler un chrome complet https://pptr.dev/
et ajouter https://www.npmjs.com/package/puppeteer-extra-plugin-stealth
pour ne pas se faire detecter
et aspirer les données du site en utilisant du javascript coté navigateur, ou carement jquery.

Je n'utilise pas ce projet, donc c'est pas vraiment une prio pour moi, mais si tu veux essayer on peut y réfléchir ensemble.

**Comment by damda58** [comment]
Tu peux utiliser Flaresolverr sinon 
https://github.com/FlareSolverr/FlareSolverr
Jackett s'en sers pour les sites protégés par Cloudflare

**Comment by rmdes** [comment]
Quid de Cloudscraper pour contourner Cloudflare ? https://pypi.org/project/cloudscraper/

**Comment by aptlt** [comment]
> Quid de Cloudscraper pour contourner Cloudflare ? https://pypi.org/project/cloudscraper/

Malheureusement inutilisable pour ygg j'ai testé, ils indiquent que le "niveau de protection" de Cloudflare est le plus haut pour ce site et qu'il faut passer par la version payante de l'outil. Mais il n'existe pas :)
